Source.create(name: 'Mark')
Source.create(name: 'Wendy')
Product.create(product_name: 'Tom Ford', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Prada', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Gucci', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Yves St.Laurent', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Versace', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Atelier', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Polo Red', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Boss', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Bulgari', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Burburry', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Legend', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Aqua di Gio', product_type: 'cologne', status: 'active')
Product.create(product_name: 'La Coste', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Issey Miyake', product_type: 'cologne', status: 'active')
Product.create(product_name: 'Invictus', product_type: 'cologne', status: 'active')